# fly.toml app configuration file generated for tesla-telemetry-server on 2024-07-28T04:06:24+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tesla-telemetry-server'
primary_region = 'syd'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  TELEMETRY_HOST = 'tesla-telemetry-server.fly.dev'
  # Use container paths for TLS certificates - these are now set as secrets
  # TLS_KEY_PATH = '/app/certs/server.key'
  # TLS_CERT_PATH = '/app/certs/server.crt'
  # TLS_CA_PATH = '/app/certs/ca.crt'
  # Set the public key server URL for the telemetry server
  PUBLIC_KEY_SERVER_URL = 'https://public-key-server-tesla.vercel.app/'
  # Path to the public key file within the container (Now set via secret)
  # PUBLIC_KEY_PATH = '/app/.well-known/appspecific/com.tesla.3p.public-key.pem'
  SERVER_TYPE = 'telemetry'
  PORT = '3000'
  # Use environment variables directly
  USE_ENV_TLS = 'true'
  # Listen on all interfaces
  LISTEN_ADDR = '0.0.0.0'

[[services]]
  internal_port = 3000
  protocol = "tcp" # The internal app speaks TCP
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[services.ports]]
    port = 443 # External HTTPS port
    handlers = ["tls", "http"] # Fly handles TLS termination and forwards HTTP

  [[services.ports]]
    port = 80 # External HTTP port
    handlers = ["http"]
    force_https = true # Redirect HTTP to HTTPS

  [[services.http_checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "60s" # Increased grace period significantly
    method = "GET"
    path = "/health"
    protocol = "http"
    port = 3000 # Check the internal port directly

[mounts]
  source = "certs"
  destination = "/app/certs"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[metrics]]
  port = 9090
  path = '/metrics'
  https = false
